"""
ECDAT End-to-End Workflow Engine.

Executes the integrated discovery-to-decision pipeline:
Input -> Ingestion -> Evidence -> Canonical Inventory -> CBOM -> Risk Analysis -> Technical Report
"""

from datetime import datetime, timezone
import hashlib
import os
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Union
import uuid

from product.core.cbom.serializer import CBOMSerializer
from product.core.domain.asset import CryptoAsset
from product.core.domain.finding import Finding
from product.core.ingestion.adapter import (
    IngestionError,
    IngestionResult,
    IngestionStatus,
    RawScannerOutput,
    ScanExecutionMetadata,
)
from product.core.ingestion.adapters.cryptoscan import CryptoScanAdapter
from product.core.ingestion.orchestrator import IngestionOrchestrator
from product.core.ingestion.registry import AdapterRegistry
from product.core.migration import MigrationScheduler, PqcTargetMapper
from product.core.migration.models import MigrationSchedule, PqcTargetMapping
from product.core.risk.models import AssetContext, MigrationPriorityRecord
from product.core.risk.pipeline import RiskAnalysisEngine
from .models import (
    Phase4AnalysisResult,
    Phase4ExecutionStatus,
    TechnicalReport,
    WorkflowRunResult,
)
from .report import TechnicalReportGenerator


class ECDATWorkflowEngine:
    """
    Coordinates the execution of ECDAT's end-to-end cryptographic discovery,
    normalization, CBOM projection, risk analysis, and report generation workflow.
    """

    def __init__(
        self,
        orchestrator: Optional[IngestionOrchestrator] = None,
        cbom_serializer: Optional[CBOMSerializer] = None,
        risk_engine: Optional[RiskAnalysisEngine] = None,
        target_mapper: Optional[PqcTargetMapper] = None,
        scheduler: Optional[MigrationScheduler] = None,
    ) -> None:
        if orchestrator is None:
            registry = AdapterRegistry()
            registry.register(CryptoScanAdapter())
            self.orchestrator = IngestionOrchestrator(registry=registry)
        else:
            self.orchestrator = orchestrator

        self.cbom_serializer = cbom_serializer or CBOMSerializer()
        self.risk_engine = risk_engine or RiskAnalysisEngine()
        self.target_mapper = target_mapper or PqcTargetMapper()
        self.scheduler = scheduler or MigrationScheduler(target_mapper=self.target_mapper)
        self.report_generator = TechnicalReportGenerator()

    def run(
        self,
        raw_input: Union[RawScannerOutput, str, bytes, Path],
        adapter_id: str = "cryptoscan",
        context: Optional[AssetContext] = None,
        target_name: Optional[str] = None,
        run_id: Optional[str] = None,
        explicit_dependencies: Optional[Union[Sequence[Tuple[str, str]], Mapping[str, Sequence[str]]]] = None,
    ) -> WorkflowRunResult:
        """
        Executes the end-to-end ECDAT pipeline on the supplied scanner output.

        Parameters:
            raw_input: A RawScannerOutput instance, a filesystem Path/str, or raw JSON bytes/str.
            adapter_id: Scanner adapter identifier (default: 'cryptoscan').
            context: Operational deployment context for risk analysis (default: AssetContext()).
            target_name: Name of the evaluated application/target (default: 'scanned-application').
            run_id: Unique analysis run identifier (default: autogenerated UUID).

        Returns:
            WorkflowRunResult containing ingestion result, findings, canonical assets,
            CycloneDX 1.7 CBOM dictionary, risk records, and auditable TechnicalReport.
        """
        effective_run_id = run_id or str(uuid.uuid4())
        effective_timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        effective_target = target_name or "scanned-application"
        effective_context = context or AssetContext()

        # Step 1: Normalize raw input into RawScannerOutput
        raw_output = self._normalize_raw_input(raw_input, adapter_id, effective_run_id, effective_timestamp)

        # Step 2: Ingestion, Normalization & Correlation
        ingestion_res, findings, assets = self.orchestrator.run_pipeline(adapter_id, raw_output)

        # Step 3: CycloneDX 1.7 CBOM Projection & Serialization
        scanner_executions = []
        if ingestion_res.scan_metadata:
            scanner_executions.append({
                "scanner_name": ingestion_res.scan_metadata.scanner_name,
                "scanner_version": ingestion_res.scan_metadata.scanner_version,
            })

        cbom = self.cbom_serializer.serialize_to_dict(
            assets=assets,
            run_id=effective_run_id,
            target_name=effective_target,
            target_hash=raw_output.sha256_hash if raw_output else None,
            timestamp=effective_timestamp,
            scanner_executions=scanner_executions,
            evidence_records=ingestion_res.evidence_records,
            findings=findings,
        )

        # Step 4: Deterministic Contextual Risk & Priority Analysis
        risk_records: List[MigrationPriorityRecord] = []
        for asset in assets:
            record = self.risk_engine.evaluate(asset, effective_context)
            risk_records.append(record)

        # Step 4A & 4B: PQC Target Mapping & Migration Scheduling (Phase 4)
        phase_4: Optional[Phase4AnalysisResult] = None
        target_mappings: Tuple[PqcTargetMapping, ...] = ()
        migration_schedule: Optional[MigrationSchedule] = None

        if not assets:
            # Honest empty execution state: No assets discovered in scope
            empty_sched = self.scheduler.schedule_migration(assets=())
            phase_4 = Phase4AnalysisResult(
                status=Phase4ExecutionStatus.SKIPPED_NO_ASSETS,
                target_mappings=(),
                migration_schedule=empty_sched,
                unsupported_hybrid_types=("DUAL_SIGNATURE", "PROTOCOL_AUTHENTICATION"),
                error_message=None,
                metadata={"reason": "No canonical cryptographic assets discovered in scan scope."},
            )
        else:
            # 4A: Target Mapping
            mapping_failed = False
            mapper_err: Optional[str] = None
            try:
                target_mappings = tuple(self.target_mapper.map_assets(assets))
            except Exception as exc:
                mapping_failed = True
                mapper_err = f"Target mapping failed: {type(exc).__name__}: {str(exc)}"

            if mapping_failed:
                phase_4 = Phase4AnalysisResult(
                    status=Phase4ExecutionStatus.FAILED,
                    target_mappings=(),
                    migration_schedule=None,
                    unsupported_hybrid_types=("DUAL_SIGNATURE", "PROTOCOL_AUTHENTICATION"),
                    error_message=mapper_err,
                )
            else:
                # 4B: Migration Scheduling
                dep_map: Optional[Dict[str, List[str]]] = None
                if explicit_dependencies is not None:
                    if isinstance(explicit_dependencies, dict):
                        dep_map = {k: list(v) for k, v in explicit_dependencies.items()}
                    elif isinstance(explicit_dependencies, (list, tuple)):
                        dep_map = {}
                        for item in explicit_dependencies:
                            if isinstance(item, (tuple, list)) and len(item) == 2:
                                prereq, dependent = item
                                dep_map.setdefault(str(dependent), []).append(str(prereq))

                sched_failed = False
                sched_err: Optional[str] = None
                try:
                    migration_schedule = self.scheduler.schedule_migration(
                        assets=assets,
                        target_mappings=target_mappings,
                        risk_assessments=risk_records,
                        explicit_dependencies=dep_map,
                    )
                except Exception as exc:
                    sched_failed = True
                    sched_err = f"Migration scheduling failed: {type(exc).__name__}: {str(exc)}"

                if sched_failed:
                    phase_4 = Phase4AnalysisResult(
                        status=Phase4ExecutionStatus.PARTIAL_FAILED,
                        target_mappings=target_mappings,
                        migration_schedule=None,
                        unsupported_hybrid_types=("DUAL_SIGNATURE", "PROTOCOL_AUTHENTICATION"),
                        error_message=sched_err,
                    )
                else:
                    phase_4 = Phase4AnalysisResult(
                        status=Phase4ExecutionStatus.COMPLETED,
                        target_mappings=target_mappings,
                        migration_schedule=migration_schedule,
                        unsupported_hybrid_types=("DUAL_SIGNATURE", "PROTOCOL_AUTHENTICATION"),
                        error_message=None,
                    )

        # Step 5: Technical Report Generation
        report: TechnicalReport = self.report_generator.generate(
            run_id=effective_run_id,
            timestamp=effective_timestamp,
            target_name=effective_target,
            ingestion_result=ingestion_res,
            findings=findings,
            assets=assets,
            cbom=cbom,
            risk_records=risk_records,
            context=effective_context,
            raw_output_sha256=raw_output.sha256_hash if raw_output else None,
            phase_4=phase_4,
        )

        # Step 6: Assemble final workflow result
        return WorkflowRunResult(
            run_id=effective_run_id,
            ingestion_result=ingestion_res,
            findings=tuple(findings),
            assets=tuple(assets),
            cbom=cbom,
            risk_records=tuple(risk_records),
            report=report,
            phase_4=phase_4,
        )

    def _normalize_raw_input(
        self,
        raw_input: Union[RawScannerOutput, str, bytes, Path],
        adapter_id: str,
        run_id: str,
        timestamp: str,
    ) -> RawScannerOutput:
        """Coerces various input types into an immutable RawScannerOutput."""
        if isinstance(raw_input, RawScannerOutput):
            return raw_input

        adapter = self.orchestrator.registry.get(adapter_id)
        scanner_name = adapter.scanner_name if adapter else "unknown"
        scanner_ver = adapter.scanner_version if adapter else "unknown"

        # Check if input is a filesystem path
        if isinstance(raw_input, Path) or (isinstance(raw_input, str) and os.path.exists(raw_input)):
            path_obj = Path(raw_input)
            try:
                stdout_bytes = path_obj.read_bytes()
                storage_ref = str(path_obj)
            except Exception as e:
                stdout_bytes = b""
                storage_ref = f"error:{e}"
            return RawScannerOutput.from_bytes(
                stdout_bytes=stdout_bytes,
                adapter_id=adapter_id,
                scanner_name=scanner_name,
                scanner_version=scanner_ver,
                scan_id=run_id,
                timestamp=timestamp,
                storage_ref=storage_ref,
            )

        # Input is raw string
        if isinstance(raw_input, str):
            stdout_bytes = raw_input.encode("utf-8")
            return RawScannerOutput.from_bytes(
                stdout_bytes=stdout_bytes,
                adapter_id=adapter_id,
                scanner_name=scanner_name,
                scanner_version=scanner_ver,
                scan_id=run_id,
                timestamp=timestamp,
                storage_ref="memory://string",
            )

        # Input is raw bytes
        if isinstance(raw_input, bytes):
            return RawScannerOutput.from_bytes(
                stdout_bytes=raw_input,
                adapter_id=adapter_id,
                scanner_name=scanner_name,
                scanner_version=scanner_ver,
                scan_id=run_id,
                timestamp=timestamp,
                storage_ref="memory://bytes",
            )

        # Fallback for unexpected type
        return RawScannerOutput.from_bytes(
            stdout_bytes=b"",
            adapter_id=adapter_id,
            scanner_name=scanner_name,
            scanner_version=scanner_ver,
            scan_id=run_id,
            timestamp=timestamp,
            storage_ref="invalid_input_type",
        )
